preload = /home/jorge/Imagens/Wallpaper/sun-god-nika-one-piece-catpuccin-lufi-gear-5th-hd-wallpaper-98063d486060cc98101c91de4852c41a.jpg
wallpaper = ,/home/jorge/Imagens/Wallpaper/sun-god-nika-one-piece-catpuccin-lufi-gear-5th-hd-wallpaper-98063d486060cc98101c91de4852c41a.jpg
