
##########################################
# CONFIGURAÇÃO MODULAR #
##########################################

souce = /opt/hyprlandconfig/hypr/conf/env.conf
source = /opt/hyprlandconfig/hypr/conf/init.conf
source = /opt/hyprlandconfig/hypr/conf/monitor.conf
source = /opt/hyprlandconfig/hypr/conf/workspaces.conf
source = /opt/hyprlandconfig/hypr/conf/audio.conf
source = /opt/hyprlandconfig/hypr/conf/screenshot.conf
source = /opt/hyprlandconfig/hypr/conf/decoration.conf
source = /opt/hyprlandconfig/hypr/conf/bindsApps.conf
# DESATIVADO source = /opt/hyprlandconfig/hypr/conf/windowApps.conf
source = /opt/hyprlandconfig/hypr/conf/cursorKeyboard.conf
source = /opt/hyprlandconfig/hypr/conf/bindsWindow.conf
source = /opt/hyprlandconfig/hypr/conf/soundboard.conf


# >>> HYPRLAND VISUAL EDITOR START <<<
# 1. Active Uninstall Watchdog
exec-once = /home/jorge/.cache/noctalia/HVE/hve_watchdog.sh
# 2. Variable Definition (Color Palette)
source = /home/jorge/.config/hypr/noctalia/noctalia-colors.conf
# 3. Effects Application (Visual Editor)
source = /home/jorge/.cache/noctalia/HVE/overlay.conf
# >>> HYPRLAND VISUAL EDITOR END <<<
