preload = /home/jorge/Imagens/Wallpaper/412679-Linux-gradient-Unix-Arch-Linux-technology-operating.png
wallpaper = ,/home/jorge/Imagens/Wallpaper/412679-Linux-gradient-Unix-Arch-Linux-technology-operating.png
