##########################
# Atalhos: Áudio e Vol.  #
##########################

# Aumentar Volume (1% por vez, limite de 100%)
bind = SUPER ALT, equal, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 1%+ && notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100 + 0.5)}')" -i audio-volume-high -u low "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100 + 0.5)"%"}')"

# Diminuir Volume (1% por vez)
bind = SUPER ALT, minus, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%- && notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100 + 0.5)}')" -i audio-volume-medium -u low "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100 + 0.5)"%"}')"