
##########################
# Atalhos: Aplicativos   #
##########################


bind = SUPER, S, exec, $ipc controlCenter toggle

bind = SUPER, P, exec, pavucontrol
bind = SUPER, k, exec, warp-terminal
bind = SUPER, T, exec, kitty

bind = SUPER, L, exec, $ipc sessionMenu toggle
bind = SUPER, D, exec, $ipc launcher toggle
bind = SUPER, B, exec, $ipc bar toggle

bind = SUPER ALT, C, exec, flatpak run com.visualstudio.code
bind = SUPER ALT, S, exec, steam
bind = SUPER ALT, N, exec, flatpak run com.brave.Browser --password-store=basic
bind = SUPER ALT, T, exec, thunar
bind = SUPER ALT, D, exec, discord
