##########################
# Execuções Automáticas  #
##########################

# 1. Definição da variável de comando para facilitar o uso (Sem o sinal de igual no Hyprland)
$ipc = qs -c noctalia-shell ipc call

# 2. Ambiente e Autenticação (Essenciais para o sistema funcionar bem)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# 3. Inicialização do Noctalia (Usando o nome da config para o IPC bater com a variável $ipc)
exec-once = qs -c noctalia-shell

# 4. Wallpaper (Usando o exec-once + sleep para dar tempo do serviço subir)
# exec-once = $ipc wallpaper set /home/jorge/Imagens/Wallpaper/412679-Linux-gradient-Unix-Arch-Linux-technology-operating.png
  


# 6. Forçar Workspace Inicial
exec-once = hyprctl dispatch workspace 1