# --- Screenshot da Tela Inteira ---
bind = SUPER, X, exec, grimblast save screen ~/Imagens/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png

# --- Screenshot de Área ---
bind = SUPER SHIFT, X, exec, grimblast save area ~/Imagens/Screenshots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png